// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HeyMx.Site {
	
	
	public partial class Login {
		
		protected System.Web.UI.WebControls.Content contentTitle;
		
		protected System.Web.UI.WebControls.Content contentHeader;
		
		protected System.Web.UI.WebControls.Content contentMain;
		
		protected System.Web.UI.WebControls.Login loginControl;
	}
}
