// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HeyMx.Site {
	
	
	public partial class Main {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder titlePlaceHolder;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder headerPlaceHoler;
		
		protected System.Web.UI.HtmlControls.HtmlForm mainForm;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder contentPlaceHolder;
	}
}
